name: Publish NuGet

on:
  push:
    tags:
      - '*'

jobs:
  publish-nuget:
    name: publish-nuget
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v5.0.0
      with:
        lfs: true
        fetch-depth: 0

    - name: "Install .NET SDK"
      uses: actions/setup-dotnet@v5.0.0
      with:
        global-json-file: "./global.json"

    - name: "Restore .NET tools"
      run: dotnet tool restore

    - name: "Update release notes"
      shell: pwsh
      run: |
        ./build.ps1

    - name: "Pack .NET tool"
      run: dotnet pack src/MSSQL.MCP/MSSQL.MCP.csproj -c Release --output ./artifacts

    - name: "Publish .NET tool"
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json" --skip-duplicate

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: 'mssql-mcp ${{ github.ref_name }}'
        tag_name: ${{ github.ref }}
        body_path: RELEASE_NOTES.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
